apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    infra_id: 2727871f-a18a-4b69-b5fe-f82ac57cdd1a
    revision_id: 042b0353-3c9a-41f2-9001-6db0fab14948
    workflow_id: 223f71f4-b717-4e1c-9a89-76ec068583b7
    workflows.argoproj.io/controller-instanceid: 2727871f-a18a-4b69-b5fe-f82ac57cdd1a
  name: sock-shop
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: sock-shop
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: sock-shop
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-faults
        template: install-chaos-faults
    - - arguments: {}
        name: pod-memory-hog-exec-i15
        template: pod-memory-hog-exec-i15
    - - arguments: {}
        name: cleanup-chaos-resources
        template: cleanup-chaos-resources
  - container:
      args:
      - kubectl apply -f /tmp/ -n {{workflow.parameters.adminModeNamespace}} && sleep
        30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-memory-hog-exec-i15
        path: /tmp/pod-memory-hog-exec-i15.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Injects memory consumption on pods belonging to an app deployment
            kind: ChaosExperiment
            metadata:
              name: pod-memory-hog-exec
              labels:
                name: pod-memory-hog-exec
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 3.10.0
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: litmuschaos.docker.scarf.sh/litmuschaos/go-runner:3.10.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-memory-hog-exec
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: MEMORY_CONSUMPTION
                    value: "500"
                  - name: PODS_AFFECTED_PERC
                    value: ""
                  - name: RAMP_TIME
                    value: ""
                  - name: CHAOS_KILL_COMMAND
                    value: kill $(find /proc -name exe -lname '*/dd' 2>&1 | grep -v 'Permission
                      denied' | awk -F/ '{print $(NF-1)}' | head -n 1)
                  - name: SEQUENCE
                    value: parallel
                  - name: DEFAULT_HEALTH_CHECK
                    value: "false"
                  - name: TARGET_CONTAINER
                    value: ""
                  - name: TARGET_PODS
                    value: ""
                labels:
                  name: pod-memory-hog-exec
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 3.10.0
    metadata: {}
    name: install-chaos-faults
    outputs: {}
  - container:
      args:
      - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.11.0
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: cleanup-chaos-resources
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-memory-hog-exec-i15.yaml
      - -saveName=/tmp/engine-name
      image: docker.io/litmuschaos/litmus-checker:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-memory-hog-exec-i15
        path: /tmp/chaosengine-pod-memory-hog-exec-i15.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              labels:
                workflow_run_id: "{{ workflow.uid }}"
                workflow_name: sock-shop
              annotations:
                probeRef: '[{"name":"s-1","mode":"Continuous"}]'
              generateName: pod-memory-hog-exec-i15
            spec:
              engineState: active
              appinfo:
                appns: sock-shop
                applabel: name=carts
                appkind: deployment
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-memory-hog-exec
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: MEMORY_CONSUMPTION
                          value: "800"
                        - name: PODS_AFFECTED_PERC
                          value: "100"
                        - name: RAMP_TIME
                          value: ""
                        - name: CHAOS_KILL_COMMAND
                          value: kill $(find /proc -name exe -lname '*/dd' 2>&1 | grep -v 'Permission
                            denied' | awk -F/ '{print $(NF-1)}' | head -n 1)
                        - name: SEQUENCE
                          value: parallel
                        - name: DEFAULT_HEALTH_CHECK
                          value: "true"
                        - name: TARGET_CONTAINER
                          value: ""
                        - name: TARGET_PODS
                          value: ""
    metadata:
      labels:
        weight: "10"
    name: pod-memory-hog-exec-i15
    outputs: {}
status:
  finishedAt: null
  startedAt: null
